services:
  app:
    image: $WORKSPACE_NAME/$APP_IMAGE
    build:
      context: $TPL_PATH/php
      args:
        - BASE_IMAGE=$BASE_IMAGE
        - GROUP_ID=$GROUP_ID
        - USER_ID=$USER_ID
    hostname: "$APP_NAME.$BASE_DOMAIN"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      VIRTUAL_HOST: "$APP_NAME.$BASE_DOMAIN"
      VIRTUAL_PORT: "80"
      HOME: /tmp/home
      COMPOSER_HOME: /tmp/home/composer
      COMPOSER_CACHE_DIR: /tmp/home/composer_cache
    working_dir: /var/www
    volumes:
      - "$SVC_PATH:/var/www"
      - "$HOME_PATH:/tmp/home"
    networks:
      - dev
  nginx:
    image: $NGINX_IMAGE
    volumes:
      - "$SVC_PATH:/var/www"
      - "$TPL_PATH/nginx/default.conf.template:/etc/nginx/templates/default.conf"
    network_mode: "service:app"
    depends_on:
      - app

networks:
  dev:
    external: true
    name: $NETWORK