services:
  app:
    image: $WORKSPACE_NAME/$APP_IMAGE
    build:
      context: $TPL_PATH/php
      args:
        - BASE_IMAGE=$BASE_IMAGE
    hostname: "$APP_NAME.$BASE_DOMAIN"
    environment:
      VIRTUAL_HOST: "$APP_NAME.$BASE_DOMAIN"
      VIRTUAL_PORT: "80"
    volumes:
      - "$SVC_PATH:/var/www"
    networks:
      - dev
  nginx:
    image: $NGINX_IMAGE
    volumes:
      - "$TPL_PATH/nginx/default.conf.template:/etc/nginx/conf.d/default.conf"
    network_mode: "service:app"
    depends_on:
      - app

networks:
  dev:
    external: true
    name: $NETWORK