name: Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3
      - name: Install tools
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0
      - name: Generate mocks
        run: |
          ./gen.sh
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...