name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.8
      # Needed for versions <1.14 tests
      - name: Install mock
        run: |
          GO111MODULE=off go get github.com/golang/mock | true
      - name: Install tools
        run: |
          go install github.com/golang/mock/mockgen
      - name: Generate mocks
        run: |
          ./gen.sh
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...